[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "sqlite"]

[phases.install]
commands = [
    "python -m ensurepip --upgrade",
    "pip install -r bot/requirements.txt",
    "pip install -r webapp/requirements.txt"
]

[start]
commands = [
    "python bot/bot.py & python webapp/app.py"
]